# Theme/colorscheme importing
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[font]
size = 15

[font.normal]
family = "MesloLGM Nerd Font"
style = "regular"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.600000

[window.padding]
x = 30
y = 30
