# Theme/colorscheme importing
import = [
    "~/.config/alacritty/themes/themes/dracula.toml",
]

[font]
size = 14

[font.normal]
family = "MesloLGM Nerd Font"
style = "regular"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.600000

[window.padding]
x = 30
y = 30
